### ISSUE TITLE
md5 check

### ISSUE THREAD

**Issue by NSP-0123456** [klslz/tuningkitpcp#1]
Latest sKit-custom-squeezelite.sh is more explicit about what it does specially when downloading.
The verification phase (md5) seems to be faulty ??

**Comment by klslz** [comment]
> Latest sKit-custom-squeezelite.sh is more explicit about what it does specially when downloading. The verification phase (md5) seems to be faulty ??

???? Please be more specific.

* describe your issue ( ...seems to be faulty ?? - won't trigger anything over here) 
* describe your setup (rpi/pcp-version)
* what have you been doing
* program revision 
* logfile 
* screenshot

THX

**Comment by NSP-0123456** [comment]
I did a sKit update from 17th ag August version to 17 of November version with Manager.
once rebooted, I call sKit-custom-squeezelite.sh
Chose 5 and 1
Downloading is OK for all tcz   
but in the integrity check is not listing tcz file nor md5checksum.


extensions integrity check

```
md5sum: can't open '/tmp/ext/*.tcz': No such file or directory
cat: can't open '/tmp/ext/*.tcz.md5.txt': No such file or directory
        integrity check:  *.tcz                                 PASSED
```
it seems that tcz files are not found in  $DOWNLOAD_DIR during chech function "verify_extensions()" line 681 for commit 7866abc033c87afadcf6087127773135f739f466

**Comment by klslz** [comment]
You didn't deliver the full info I asked for.

I did some minor changes anhow.

Give it a try.

On my installation it works fine.

Attach the corresponding log next time.

**Comment by NSP-0123456** [comment]
All is working fine now.
I removed custom binaries and then reinstalled after reboot to force download again. 
The quote line 696 did the trick.

Thanks a lot....

**Comment by klslz** [comment]
Good to see you made it. I do find it strange that it worked for me, without that change. I mean. It's supposedly the same environment and shell we're looking at.

Anyhow. Enjoy.
